account:
  account_server:
    grpc_server_port: 23500
  account_web:
    port: 23501


database:
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "account_srv_db"
  charset: "utf8mb4"
  parse_time: "True"
  loc: "Local"
  log_path: "./logs/db.log"
  log_level: "info"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600


jwt:
  secret: "34ed12de9dbd2a72d6486790efe116ac"

logger:
  level: "debug"
  filename: "./logs/app.log"
  max_size: 50
  max_backups: 7
  max_age: 30
  compress: true
  console: true
  json: false
  color: true
